### PR TITLE
bump protobufs to v21

### PR DESCRIPTION
**Pull request by jbergler**
A possible solution for https://github.com/authzed/authzed-py/issues/67

### CODE REVIEW

**Comment by jbergler** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jbergler** [comment]
recheck

**Comment by samkim** [comment]
Thanks for the PR! I'll do some testing and checkout the breaking changes you mentioned in the issue.

**Comment by jbergler** [comment]
No worries, I tried to fixup the diffs in the generated files by bumping the version of `buf` but I'm only guessing thats the issue. If you have ideas on what I should do to fix it properly I'm all ears.

**Review by samkim — APPROVED** [review]
LGTM and the breaking changes in v21 don't seem to impact our usage. 

Fixes https://github.com/authzed/authzed-py/issues/67

**Pull request merged**
