### PR TITLE
Update to the latest protobuf version

### PR DESCRIPTION
**Pull request by nsotelo**
This includes new features such as LookupSubjects in the permissions service.

Signed-off-by: Nigel Sotelo <nigel.sotelo@nccgroup.com>

### CODE REVIEW

**Comment by nsotelo** [comment]
recheck

**Comment by vroldanbet** [comment]
Hey! FYI I'm trying to revamp the buf's CI builds in https://github.com/authzed/authzed-py/pull/43 to reuse our centralized GitHub Action - may fix some problems with failing buf build

**Comment by vroldanbet** [comment]
Hey! FYI I'm trying to revamp the buf's CI builds in https://github.com/authzed/authzed-py/pull/43 to reuse our centralized GitHub Action - may fix some problems with failing buf build

**Comment by nsotelo** [comment]
@vroldanbet Thank you

**Pull request closed without merging**
