### PR TITLE
Include re-exports in pyi file

### PR DESCRIPTION
**Pull request by mateenkasim**
- The recent addition of the `__init__.pyi` file means VSCode's Pylance looks to that file for static analysis, rather than the `.py` file.
- This PR copies re-exports to the `.pyi` file, allowing VSCode to resolve re-exported paths such as this:

```python
from authzed.api.v1 import CheckPermissionRequest

# Without this PR, Pylance only resolves this path
# from authzed.api.v1.permission_service_pb2 import CheckPermissionRequest
```

### CODE REVIEW

**Comment by mateenkasim** [comment]
Any thoughts on this one? It's pretty clunky to have to write imports like this to get type hints:
```python
from authzed.api.v1.core_pb2 import RelationshipUpdate, SubjectReference
from authzed.api.v1.experimental_service_pb2_grpc import ExperimentalServiceStub
from authzed.api.v1.permission_service_pb2 import (CheckBulkPermissionsRequest, CheckBulkPermissionsRequestItem,
                                                   CheckBulkPermissionsResponse, CheckPermissionRequest,
                                                   CheckPermissionResponse, Consistency, DeleteRelationshipsRequest,
                                                   DeleteRelationshipsResponse, WriteRelationshipsRequest,
                                                   WriteRelationshipsResponse)
from authzed.api.v1.permission_service_pb2_grpc import PermissionsServiceStub
from authzed.api.v1.schema_service_pb2_grpc import SchemaServiceStub
from authzed.api.v1.watch_service_pb2_grpc import WatchServiceStub
```

**Comment by tstirrat15** [comment]
@mateenkasim I'm a new maintainer and I'm also not super familiar with python library conventions around typing and interfaces. Is this a common pattern? It also looks like this is manually extending something that was manually created - does that match your understanding?

Do the import paths for the annotations match the import paths for the actual objects? Do they need to?

I think I'm generally good with this approach, but I want to make sure I understand the how and the why of it.

**Comment by mateenkasim** [comment]
Sure, I'll put my understanding. The interfaces, or stubs, are meant to be a stripped-down version of the code itself, where the module path and code structure is the same, but implementation is missing. This gives something clean off of which you (or static-analyzers, like type-checkers) can read the type information. Sometimes types are enhanced in the stub file compared to the code file itself, since that's where analyzers are looking anyway. Example from an established project:
- Django file for QuerySets: https://github.com/django/django/blob/main/django/db/models/query.py
- Django stub file for QuerySets: https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/query.pyi

This can also _hide_ information that you didn't intend to be publicly used, like imports of 3rd-party libraries that you need to use but don't want to re-export. In that case, you just don't put the import in the stub file.

In this case, I haven't checked the motivation or details of why `__init__.pyi` exists in the first place (maybe I should?). The Client/AsyncClient stuff isn't mine, so I didn't touch it. I do know it appeared here.
- https://github.com/authzed/authzed-py/pull/149
- https://discord.com/channels/844600078504951838/844600078948630559/1222604495867875369

All I know is that, _if_ there is going to be a stub file in the first place, then it will need all the type/import information that we wanted publicly available from the implementation file.

**Comment by tstirrat15** [comment]
Okay, that makes sense. I had a look too at what's autogenerated vs manually generated, and it looks like the current python protoc tooling doesn't create a `__init__.py` file anyway, so that was something that we built by hand. It looks like all you're doing in the `pyi` file is bringing it in line with what's in `__init__.py` and I'm here for it. I'm gonna go ahead and accept and merge this.

I'll talk with the team on Monday about getting a release cut.

**Comment by tstirrat15** [comment]
One last question: if the `.pyi` file didn't exist and we just typed the `__init__.py` file, would it autodiscover? I suppose we can do that in future work if desird.

**Review by tstirrat15 — APPROVED** [review]
These changes LGTM.

**Pull request merged**
